[profile.default]
src = "src"
out = "out"
libs = ["lib"]
no_match_test = 'FFI'
fs_permissions = [{ access = "write", path = "./deployments" }]
ignored_warnings_from = ["lib"]

[profile.ffi]
src = "src"
out = "out"
libs = ["lib"]
match_test = 'FFI'
ffi = true
ignored_warnings_from = ["lib/aave-v3-core"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
  sepolia = "https://sepolia.infura.io/v3/${API_KEY_INFURA}"
  base = "https://base-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  anvil = "http://127.0.0.1:8545"

[etherscan]
  sepolia = { key = "${API_KEY_ETHERSCAN}" }
  base = { key = "${API_KEY_ETHERSCAN}" }
