name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-c3069a50ba18cccfc4e7d5de9b9b388811d9cc7b

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv --no-match-test FFI
        id: test

  fmt:
    strategy:
      fail-fast: true

    name: Forge Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-c3069a50ba18cccfc4e7d5de9b9b388811d9cc7b

      - name: Format
        run: |
          forge fmt --check
        id: fmt

  abi:
    strategy:
      fail-fast: true

    name: ABI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-c3069a50ba18cccfc4e7d5de9b9b388811d9cc7b

      - name: ABI
        run: |
          forge build --build-info

      - name: Archive ABI
        uses: actions/upload-artifact@v4
        with:
          name: abi
          path: |
            out/FlashLoanLiquidation.sol/FlashLoanLiquidator.json
            out/PeripheryErrors.sol/PeripheryErrors.json
            out/MarketMakerManagerFactory.sol/MarketMakerManagerFactory.json
            out/MarketMakerManager.sol/MarketMakerManager.json
